# Generated by Django 5.0.4 on 2024-04-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verseNum', models.PositiveIntegerField()),
                ('chapterNum', models.PositiveIntegerField()),
                ('bookNum', models.PositiveIntegerField()),
            ],
        ),
    ]
